services:
  postgres:
    image: postgres:15
    container_name: taskapp_db
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  postgres_data: